### ISSUE TITLE
Some backs are impossible to change in the UI

### ISSUE THREAD

**Issue by duckyb** [chilli-axe/mpc-autofill#104]
When the xml file includes a `<backs>` tag, it's impossible to change the back of some cards without editing the XML directly.

![image](https://user-images.githubusercontent.com/27895007/200418572-2cd91d04-11c9-4585-8005-2e154b5e9fe2.png)

```xml
<order>
  <details>
    ...
  </details>
  <fronts>
    ...
  </fronts>
  <backs>
    <card>
      <id>1LrVX0pUcye9n_0RtaDNVl2xPrQgn7CYf</id>
      <slots>36,34,31,35,33,32</slots>
      <name>Black Lotus.png</name>
      <query></query>
    </card>
  </backs>
  <cardback>1MZAjDx0OrqB9SxqeQLHo5sqPDxHmMMn0</cardback>
</order>
```

This happened accidentally when exporting/importing XML orders and I had to open the XML to fix it.

**Comment by ndepaola** [comment]
this is a known design flaw with the frontend and was a tradeoff made to support multiple cardbacks. i'm currently redesigning the frontend and will make sure this work flow is accounted for properly. i'm sorry this inconvenienced you!

**Comment by ndepaola** [comment]
this item is fixed in the new frontend - i'll close this issue once the new frontend is ready for public use

**Comment by tarragoesteve** [comment]
New occurrence:
![image](https://github.com/chilli-axe/mpc-autofill/assets/6769897/afe85510-9bc0-4277-816f-f405a0f1742d)

In previous releases, I was able to select a different card back for all cards. I used this feature to do double-faced tokens.

**Comment by ndepaola** [comment]
the public beta is available now - you can access it with the mpcfill.com database at https://mpcautofill.github.io?server=https://mpcfill.com - where this issue is fixed.
