### ISSUE TITLE
Feature request: wakelock (prevent system sleep)

### ISSUE THREAD

**Issue by duckyb** [chilli-axe/mpc-autofill#108]
When uploading large quantities of images to MPC, the process can take multiple hours. My last order consisted of two 504 card orders which took 10 hours each to upload.

It would be beneficial to be able to leave the system and the script running while away or overnight. Unfortunately, the system can still go into deep sleep after a while unless the user changes the system settings, causing the script to freeze itself and risking a complete loss of progress.

## Problem

- If the system goes into a deep sleep state, the script will freeze itself

## Workarounds

- Change the system settings to prevent the system from hibernating itself
- Use _PowerToys Awake_ to wakelock the system (Windows)

## Proposed solutions

- Add a CLI flag to wakelock the system while the script is running
- Keep the system awake by default

Warn the user about this setting along with the other info shown at runtime

### Example of frozen script / website after 9 hours of execution

![image](https://user-images.githubusercontent.com/27895007/202047935-a0aaf270-8686-4371-b638-91fd103d4dcf.png)

Notice how the website has a gray overlay that prevents any interaction. This overlay had to be removed via DOM inspector in order to save the progress.

**Comment by ndepaola** [comment]
sounds good - i looked into this briefly and found this library https://github.com/np-8/wakepy - should be a straightforward addition to the tool.

**Comment by AitanBachrach** [comment]
If no one has started on this issue may I?

**Comment by ndepaola** [comment]
> If no one has started on this issue may I?

nobody has started on this yet, go for it 😊

**Comment by ndepaola** [comment]
fixed by https://github.com/chilli-axe/mpc-autofill/pull/131
