### ISSUE TITLE
running autofill.exe with a cards.xml that contains utf-8 characters raises error

### ISSUE THREAD

**Issue by lukegothic** [chilli-axe/mpc-autofill#110]
Unable to process the attached cards.xml, shows error below
Probably caused by UTF-8 characters present inside .xml

![image](https://user-images.githubusercontent.com/3224037/202162654-8419812c-4aec-4bcb-9810-b6abf7ec4672.png)

[cards.zip](https://github.com/chilli-axe/mpc-autofill/files/10020924/cards.zip)

**Comment by lukegothic** [comment]
Opening in Chrome as provided in the zip:
![image](https://user-images.githubusercontent.com/3224037/202175333-45dcce40-e6ce-4e46-a31c-cc4b6ae8e5b2.png)
Opening after adding a trailing space and saving:
![image](https://user-images.githubusercontent.com/3224037/202175459-332a35af-1d9c-4be9-890e-2e49ad58e14f.png)
Opening after removing â and ú:
![image](https://user-images.githubusercontent.com/3224037/202175573-b3765de6-dba1-4f21-9b1e-a42dda56ca2f.png)

**Comment by lukegothic** [comment]
Could it be that the file must have a proper encoding? (utf-8) or something like that?

**Comment by ndepaola** [comment]
weird - here's how it looked on my machine (checked in both firefox and chrome):
<img width="1052" alt="image" src="https://user-images.githubusercontent.com/3079166/202176043-f902d43a-9bf1-4fbe-9953-729c1ae68383.png">
xml file attached (had to change the extension to `txt` so github wouldn't complain)
[cards.txt](https://github.com/chilli-axe/mpc-autofill/files/10021399/cards.txt)

macos finder shows a 6 byte difference between your file and my re-saved one:
<img width="545" alt="image" src="https://user-images.githubusercontent.com/3079166/202176282-7512fc3c-e7c7-4493-b988-35a821aa4b64.png">

this project uses `defusedxml` and looking at the source code for that, it appears it relies on the python standard library `xml` parse method https://github.com/tiran/defusedxml/blob/main/defusedxml/ElementTree.py#L130 which the docs for are here: https://docs.python.org/3/library/xml.etree.elementtree.html#xml.etree.ElementTree.XMLParser

**Comment by ndepaola** [comment]
awesome! glad to hear it's working for you now 🥰
