### ISSUE TITLE
Paging to Backs fails using --skipsetup

### ISSUE THREAD

**Issue by DagonX** [chilli-axe/mpc-autofill#116]
When using --skipsetup to continue an order, I keep getting this error after the tool confirms that all the fronts are in place and tries to navigate to "Customize Back":
```
An uncaught exception occurred: Message: no such window
  (Session info: chrome=[IP Adress removed for privacy reasons])
Stacktrace:
Backtrace:
        (No symbol) [0x00A36643]
        (No symbol) [0x009CBE21]
        (No symbol) [0x008CD960]
        (No symbol) [0x008BF941]
        (No symbol) [0x008BDE7E]
        (No symbol) [0x008BE647]
        (No symbol) [0x008D7958]
        (No symbol) [0x008D0477]
        (No symbol) [0x008CFFAF]
        (No symbol) [0x008D0842]
        (No symbol) [0x008D12E5]
        (No symbol) [0x009379F7]
        (No symbol) [0x0091FD7C]
        (No symbol) [0x00936B09]
        (No symbol) [0x0091FB76]
        (No symbol) [0x008F49C1]
        (No symbol) [0x008F5E5D]
        GetHandleVerifier [0x00CAA142+2497106]
        GetHandleVerifier [0x00CD85D3+2686691]
        GetHandleVerifier [0x00CDBB9C+2700460]
        GetHandleVerifier [0x00AE3B10+635936]
        (No symbol) [0x009D4A1F]
        (No symbol) [0x009DA418]
        (No symbol) [0x009DA505]
        (No symbol) [0x009E508B]
        BaseThreadInitThunk [0x755EF989+25]
        RtlGetAppContainerNamedObjectPath [0x775E5DE4+228]
        RtlGetAppContainerNamedObjectPath [0x775E5DB4+180]
```

From what I can tell, the page to modify the backs loads normally and I can manually upload images or drag and drop them into spaces. The error appears long before the page is fully loaded, though.

**Comment by Loonzar** [comment]
Hey,

Made an account to be able to give input! i'm experiencing the exact same error.
This is my results:

1. Start program with --skipsetup
2. Sign in and select project
3. Let page load fully 
4. Move to customize front & back to get any pop-ups out of the way
5. Navigate to customize Front, and start the program
6. it does its thing and continues successfully, confirming all images have ben assigned to each card then attempts to move to customize back
7. The page loads slowly and gets to "Ad text To Front" then the program crashes.

Backtrace:ing to Backs, Action: N/A
        (No symbol) [0x00586643]
        (No symbol) [0x0051BE21]
        (No symbol) [0x0041D960]
        (No symbol) [0x004523A7]
        (No symbol) [0x00446B13]
        (No symbol) [0x0046FD7C]
        (No symbol) [0x0044641F]
        (No symbol) [0x004700D4]
        (No symbol) [0x00486B09]
        (No symbol) [0x0046FB76]
        (No symbol) [0x004449C1]
        (No symbol) [0x00445E5D]
        GetHandleVerifier [0x007FA142+2497106]
        GetHandleVerifier [0x008285D3+2686691]
        GetHandleVerifier [0x0082BB9C+2700460]
        GetHandleVerifier [0x00633B10+635936]
        (No symbol) [0x00524A1F]
        (No symbol) [0x0052A418]
        (No symbol) [0x0052A505]
        (No symbol) [0x0053508B]
        BaseThreadInitThunk [0x765600F9+25]
        RtlGetAppContainerNamedObjectPath [0x77847BBE+286]
        RtlGetAppContainerNamedObjectPath [0x77847B8E+238]

**Comment by kkilden** [comment]
Same here

**Comment by ndepaola** [comment]
sorry about this fellas and thank you for the detailed bug reports. not completely sure why we're hitting this error here, but handling the exception works reliably on my machine. tested on both creating a new order and continuing an existing order. fix here: https://github.com/chilli-axe/mpc-autofill/commit/75bc27b6d22b8e870f5d2ca7a7b2714a9b36bd04 and there will be a release containing the fix shortly.

**Comment by jbom1** [comment]
I'm getting a similar error on the latest release. All my fronts are done on my saved project.

1. Run autofill-windows.exe --skipsetup
2. Log in and navigate to the Customize Front page of the project.
4. Return to program window and press Enter
5. Program brings up "enter number of cards" window
6. Program crashes with the following error:

An uncaught exception occurred: Message: javascript error: Cannot read properties of null (reading '492')
  (Session info: chrome=[removed])
Stacktrace:
Backtrace:
        (No symbol) [0x00CB37D3]
        (No symbol) [0x00C48B81]
        (No symbol) [0x00B4B36D]
        (No symbol) [0x00B4E0FB]
        (No symbol) [0x00B4DFD0]
        (No symbol) [0x00B4EA35]
        (No symbol) [0x00BB209F]
        (No symbol) [0x00B9B41C]
        (No symbol) [0x00BB1215]
        (No symbol) [0x00B9B216]
        (No symbol) [0x00B70D97]
        (No symbol) [0x00B7253D]
        GetHandleVerifier [0x00F2ABF2+2510930]
        GetHandleVerifier [0x00F58EC1+2700065]
        GetHandleVerifier [0x00F5C86C+2714828]
        GetHandleVerifier [0x00D63480+645344]
        (No symbol) [0x00C50FD2]
        (No symbol) [0x00C56C68]
        (No symbol) [0x00C56D4B]
        (No symbol) [0x00C60D6B]
        BaseThreadInitThunk [0x75BB00F9+25]
        RtlGetAppContainerNamedObjectPath [0x77B77BBE+286]
        RtlGetAppContainerNamedObjectPath [0x77B77B8E+238]

**Comment by friederschueler** [comment]
Same issue here. All my fronts are done and saved, but I can not go to backs :(

1. Run autofill-windows.exe --skipsetup
2. Log in and navigate to the Customize Front page of the project.
3. Return to program window and press Enter

```The program has been started with --skipsetup, which will continue
uploading cards to an existing project. Please sign in to MPC and select an existing project
to continue editing. Once you've signed in and have entered the MPC project editor, return to
the console window and press Enter.

An uncaught exception occurred: Message: javascript error: oDesign is not defined
  (Session info: chrome=110.0.5481.178)
Stacktrace:
Backtrace:
        (No symbol) [0x00F037D3]
        (No symbol) [0x00E98B81]
        (No symbol) [0x00D9B36D]
        (No symbol) [0x00D9E0FB]
        (No symbol) [0x00D9DFD0]
        (No symbol) [0x00D9EA35]
        (No symbol) [0x00E0209F]
        (No symbol) [0x00DEB41C]
        (No symbol) [0x00E01215]
        (No symbol) [0x00DEB216]
        (No symbol) [0x00DC0D97]
        (No symbol) [0x00DC253D]
        GetHandleVerifier [0x0117ABF2+2510930]
        GetHandleVerifier [0x011A8EC1+2700065]
        GetHandleVerifier [0x011AC86C+2714828]
        GetHandleVerifier [0x00FB3480+645344]
        (No symbol) [0x00EA0FD2]
        (No symbol) [0x00EA6C68]
        (No symbol) [0x00EA6D4B]
        (No symbol) [0x00EB0D6B]
        BaseThreadInitThunk [0x77B100F9+25]
        RtlGetAppContainerNamedObjectPath [0x77E27BBE+286]
        RtlGetAppContainerNamedObjectPath [0x77E27B8E+238]

Press Enter to exit.
```
