### ISSUE TITLE
Is there any interest in rewriting the frontend app?

### ISSUE THREAD

**Issue by mcapu** [chilli-axe/mpc-autofill#119]
Hi,

Historically, I've seen some improvements that I believe could be made to the current UI, such as:

* Reordering slots
* Duplicating slots
* Zooming in on cards while picking a version without needing to select it and then go back to the "list" view
* Filtering by creator/drive without the need to reload the page
* Saving state between sessions
* Undoing (at least for certain operations, such as slot deletion)

Aside from this, the current code is written in plain JS with `jQuery` and it feels a bit harder to add features to it than to rearchitect it from scratch. After taking a quick look at it, I was thinking about writing my own implementation for personal usage. However, it might be a better idea if we could align on this and get to a shared solution to which I could contribute and that could be used by more people. Please let me know if you'd be open to start such a project or if you'd prefer to keep it as-is.

PS: it might be a good idea to open up GitHub discussions for this project. This kind of issues make more sense as discussions to me, but I had no choice.
PS2: great project, thanks for all the effort.

**Comment by mcapu** [comment]
Actually, I just found the `reachitect-django-project` branch, so I'll take a look at it there.

**Comment by ndepaola** [comment]
hey, thanks for posting this :) i agree the current frontend isn't ideal and i've made some progress towards rewriting it in react. it's promising so far but still a fair amount more work required, and i'm finding it hard to put time towards it between full time work and health issues atm. i'll look into moving my project management over to github and opening the discussions board for better transparency here :)
