### ISSUE TITLE
ValueError on Autofill.exe

### ISSUE THREAD

**Issue by jacobtorbeck** [chilli-axe/mpc-autofill#12]
![5531C056-9C57-4D44-B045-D311A550D741](https://user-images.githubusercontent.com/78767132/107293845-f4ec4a00-6a31-11eb-928b-4979309e9f9c.png)

everything has been downloaded into the same folder... what’s gone awry?

the address mentioned is for a driver about 22 versions behind and navigating to the url doesn’t find a driver.  Any help?

**Comment by ndepaola** [comment]
totally forgot to look into this sorry. pls reopen if the issue persists on the latest release
