### ISSUE TITLE
Unable to login using B2C Google identity

### ISSUE THREAD

**Issue by diegopozzi1** [chilli-axe/mpc-autofill#150]
Hello,
I'm trying to use the tool but Google B2C login fails due "unsecure" browser, considering the error, maybe it can't be fixed but it would like to be reported in the guide, I spent a day uploading hundreds of cards and lost the project due this failure.

![2023-06-15](https://github.com/chilli-axe/mpc-autofill/assets/93269508/a12c1531-828c-43df-b649-055cb609b6fd)

**Comment by ndepaola** [comment]
hey there, sorry for the inconvenience this caused you. this is unfortunately a limitation of browsers controlled with automation software. i call this issue out in the wiki here https://github.com/chilli-axe/mpc-autofill/wiki/Desktop-Tool#overview and recommend that you create a makeplayingcards account prior to running the tool. open to any feedback on how the docs could be improved to reduce the chance of people missing this though.

**Comment by diegopozzi1** [comment]
Hi, thanks for confirmation, as I supposed it can't be fixed. The guide here is clear, but it would be useful to add this warning here too: https://mpcfill.com/guide

**Comment by ndepaola** [comment]
> Hi, thanks for confirmation, as I supposed it can't be fixed. The guide here is clear, but it would be useful to add this warning here too: https://mpcfill.com/guide

addressed by [commit #2f1623f679cafec9883647af4ccde40084dcc765](https://github.com/chilli-axe/mpc-autofill/commit/2f1623f679cafec9883647af4ccde40084dcc765)
