### ISSUE TITLE
Desktop Tool Not working properly with Chrome 115.0.5790?

### ISSUE THREAD

**Issue by HenriLamarre** [chilli-axe/mpc-autofill#154]
When launching the desktop tool for windows, I now get the error:
![image](https://github.com/chilli-axe/mpc-autofill/assets/59838556/7b34af5a-aef1-4a91-9e8d-115e82a3d78d)

Is this because of the new version of chrome? The tool used to work for me a few months back.
Thanks.

**Comment by ndepaola** [comment]
g'day, thanks for raising this, I wasn't aware of this issue. looks like it's on `webdriver-manager`'s side - see https://github.com/SergeyPirogov/webdriver_manager/issues/538 and https://github.com/SergeyPirogov/webdriver_manager/pull/537. when the linked PR is merged, I'll update the tool to use that version and put out a new release. sorry for the inconvenience!!

**Comment by ndepaola** [comment]
fixed in the latest release ☺️
