### ISSUE TITLE
Having trouble running the application on MacOS High Sierra 10.13.6

### ISSUE THREAD

**Issue by AidanTeran** [chilli-axe/mpc-autofill#156]
I am having an issue running the application on my macbook, a screenshot of the output has been attached. i am not very good at this stuff and am wondering if the solution is as simple as installing a new version of python. Please help if possible! Thanks!
<img width="564" alt="Screen Shot 2023-07-26 at 10 41 38 AM" src="https://github.com/chilli-axe/mpc-autofill/assets/28277381/9e743bb6-c0bd-402d-86f1-fde10906c7ae">

**Comment by ndepaola** [comment]
g'day - what version of macOS are you running? there's a documented limitation in the wiki here https://github.com/chilli-axe/mpc-autofill/wiki/Desktop-Tool#macos that says that the tool may not work on older versions of macos. this isn't really within my control unfortunately - it's a limitation of pyinstaller (the build system we use) as documented here https://pyinstaller.org/en/stable/usage.html#making-mac-os-x-apps-forward-compatible and the app is built on github actions, which (to my understanding) cannot be run on an older version of macos

**Comment by ndepaola** [comment]
i didn't see initially that you posted your OS version in the title 😅 i'm pretty confident that's the issue here. i understand that this can be intimidating for some users, but the only workaround here that im  aware of is to download and run the source code directly
