### ISSUE TITLE
Windows Defender is detecting a Trojan

### ISSUE THREAD

**Issue by madshi42** [chilli-axe/mpc-autofill#158]
Hi With the new release Widnows defender is detecting a security risk (Trojan:Win32/Wacatac.B!ml)

**Comment by ndepaola** [comment]
g'day. this is unfortunately an issue with pyinstaller (the build system we use) - see this thread https://github.com/pyinstaller/pyinstaller/issues/5492 totally understand if you're not comfortable running the program with this warning from windows defender - in that case, i recommend downloading, reading, then running the python source code directly. i'll add an item to the backlog for investigating the process of submitting the exe to antivirus companies for review

**Comment by ndepaola** [comment]
i've submitted the exe from the latest release to microsoft to review - will post again when there's an update to share

**Comment by ndepaola** [comment]
![image](https://github.com/chilli-axe/mpc-autofill/assets/3079166/68a84cce-542d-4f52-8473-1b82de4741f4)
![image](https://github.com/chilli-axe/mpc-autofill/assets/3079166/980da5b9-e8b9-4f18-b6b7-82fe642a599b)
