### ISSUE TITLE
Autofill does not find Brave browser

### ISSUE THREAD

**Issue by GriceTurrble** [chilli-axe/mpc-autofill#16]
- OS: Windows 10 64-bit
- Version: latest autofill.exe from release 3.2

I don't have Chrome installed on this machine, as I use Brave browser by choice. I would prefer not to have to install Chrome in order to get that working.

Traceback shows:

```
PS C:\dev\projects\mtg\order_001> .\autofill.exe
MPC Autofill initialising.
Successfully read XML file. Starting card downloader and webdriver processes.
ERROR: The system was unable to find the specified registry key or value.
Traceback (most recent call last):
  File "autofill.py", line 430, in <module>
  File "site-packages\webdriver_manager\chrome.py", line 28, in __init__
  File "site-packages\webdriver_manager\driver.py", line 54, in __init__
  File "site-packages\webdriver_manager\utils.py", line 142, in chrome_version
ValueError: Could not get version for Chrome with this command: reg query "HKEY_CURRENT_USER\Software\Google\Chrome\BLBeacon" /v version
[15988] Failed to execute script autofill
```

Likely this is a problem for [webdriver_manager](https://github.com/SergeyPirogov/webdriver_manager) to try to solve if you wanted to continue using it.

Alternatively, can you catch that exception and fall back to setting up the driver manually, allowing me to select Brave's binary myself? Selenium should be able to use it with the same Chrome driver (see [this SO question](https://stackoverflow.com/questions/47158434/how-to-run-selenium-tests-on-the-brave-web-browser/55901120#55901120)).

**Comment by ndepaola** [comment]
support for brave and edge: https://github.com/chilli-axe/mpc-autofill/commit/34ac75162a8fbb2aa9ff40d39994e5f98f359fbd
