### ISSUE TITLE
uncaught exception with chrome

### ISSUE THREAD

**Issue by david52398** [chilli-axe/mpc-autofill#160]
An uncaught exception occurred: An error occurred while attempting to configure the webdriver for your specified browser. Please make sure you have installed the browser and that it is up to date:

There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_115.0.5790
Press Enter to exit.
Images Uploaded   0%|                                                                          |  0/90 [00:00<?, 0.00/s]Images Downloaded   0%|                                                                        |  0/90 [00:00<?, 0.00/s]State: Initialising, Action: N/A      

I have ensured chrome is completely up to date, it would seem its looking for an older version of chrome?

**Comment by ndepaola** [comment]
are you using the latest release? https://github.com/chilli-axe/mpc-autofill/releases/tag/v4.3.2 this should already be fixed

**Comment by david52398** [comment]
I must have missed the release. Apologies!

**Comment by ndepaola** [comment]
all good!
