### ISSUE TITLE
Dowloading Excess Images

### ISSUE THREAD

**Issue by Torrero69** [chilli-axe/mpc-autofill#166]
![uu66WDV](https://github.com/chilli-axe/mpc-autofill/assets/142627094/e6e8bb57-5d45-44b2-a65e-320be07a73b4)

# Description
While trying to download a full set up the pathway lands, 10 cards front and back, so 20 cards total, you are instead prompted with a download of 31 images, instead of 21. 

21 would be 20 images for the lands and one "card back", but in the 31 images you get that plus 10 other images that were not selected. 

# Steps to Reproduce

Input list of 20 pathways
Barkchannel Pathway
Tidechannel Pathway
Blightstep Pathway
Searstep Pathway
Branchloft Pathway
Boulderloft Pathway
Brightclimb Pathway
Grimclimb Pathway
Clearwater Pathway
Murkwater Pathway
Cragcrown Pathway
Timbercrown Pathway
Darkbore Pathway
Slitherbore Pathway
Hengegate Pathway
Mistgate Pathway
Needleverge Pathway
Pillarverge Pathway
Riverglide Pathway
Lavaglide Pathway

Select the Chili_Axe full art variant for each one

Download images

**Comment by ndepaola** [comment]
thanks for posting the extra detail here - i now understand what's going on. this isn't a software bug but is a misalignment of expectations:

* the project includes a DFC matching system where, if you input a query for the front of a DFC pair (and you didn't specify a query for the back of that slot), the site will automatically set its back query to the back of that DFC pair
* we don't do any DFC matching if you type in the back of a DFC pair as a front query 
* e.g. if you type in Barkchannel Pathway, the site will automatically associate it with Tidechannel Pathway; if you type in Tidechannel Pathway, you will get the default cardback
* let's use Barkchannel / Tidechannel to illustrate how you're getting extra images in your download:
    * you're starting by typing in *both* Barkchannel Pathway and Tidechannel Pathway
    * so you end up with both cards in your fronts, but Barkchannel Pathway is also mapped to Tidechannel Pathway
    * all of them are set to the first search result, so the front and back versions of Tidechannel Pathway are the same
    * if you try to download all images, you will get 3 images - both pathways and the project cardback
    * next, you are changing the selected versions to the full art versions for your fronts, and the back Tidechannel Pathway remains on the default version
    * you now have 4 unique images in your project to download
* to get it to work the way you expect, don't manually type in the back faces as their own lines; let the site match the backs for you
