### ISSUE TITLE
Uncaught exception - No such driver version 116.1.57.49 for win32

### ISSUE THREAD

**Issue by ongchinkai** [chilli-axe/mpc-autofill#168]
# System

- **Operating System (including version)**: Windows 11 Home
- **Desktop Tool Version**: 4.3.2
- **Browser (including version)**: Brave "Version 1.57.49 Chromium: 116.0.5845.96 (Official Build) (64-bit)"

# Affected Components

- [ ] Backend
- [ ] Frontend
- [x] Desktop Tool

# Description

An uncaught exception occurred:
No such driver version 116.1.57.49 for win32

# Steps to Reproduce

Project XML can be found at https://pastebin.com/krytswPs - using this as there are 222 cards in the project.

**Comment by ndepaola** [comment]
g'day - this is mentioned in the latest release's notes here https://github.com/chilli-axe/mpc-autofill/releases/tag/v4.3.2 unfortunately brave is broken in the library we use for webdriver management, not much i can do about this until it's fixed on their end :( i raised this issue with `webdriver_manager` a few weeks ago here: https://github.com/SergeyPirogov/webdriver_manager/issues/579 are you able to use chrome or edge instead?

**Comment by ndepaola** [comment]
an update from the `webdriver_manager` developer - not the news i was hoping to hear:
![image](https://github.com/chilli-axe/mpc-autofill/assets/3079166/7f06e2d3-b5a5-4da9-872d-c9f0618f6002)

**Comment by ongchinkai** [comment]
Sorry but what does PR mean here?

**Comment by ndepaola** [comment]
a pull request (PR) is how code is contributed to open source projects - he's telling me and other people who rely on brave support to fix it themselves

**Comment by ndepaola** [comment]
some movement on this issue (see the linked PR) - selenium (the library we use for interacting with your browser) has rolled out a new system for natively managing webdrivers, so i'm going to switch to that if possible https://www.selenium.dev/documentation/selenium_manager/
