### ISSUE TITLE
Cards with name starting with X are added without the X

### ISSUE THREAD

**Issue by AmauryLepicard** [chilli-axe/mpc-autofill#172]
On mpcfill.com, when adding a card via the text box, if a card name starts with X, the search will remov the X, and as a result fail to find the card.

# Steps to Reproduce
Click "Add Cards/Text"
Add;
Xenk, Paladin Unbroken
Xenagos, the Reveler
in the text box

The search will try to find "enk, Paladin Unbroken" and "enagos, the Reveler" and fails as a result

If I add a number before, the problem is resolved

-

**Comment by ndepaola** [comment]
thanks for letting me know! whoops 😅 looks like this only affects the beta frontend and not the old frontend. will fix this later
