### ISSUE TITLE
Allow adding a name variable for cardback selection

### ISSUE THREAD

**Issue by DonutCables** [chilli-axe/mpc-autofill#19]
Oops that hitting enter too soon.

Right now card backs are determined in cards.xml by the <cardback> tag alone. This makes it either difficult or just troublesome to use local image files for custom cardbacks with the autofill app. Allowing adding a <name> tag inside of <cardback> would be a cleaner way to just dictate a local filename to be used for a cardback if someone doing a more custom order setup required it.

**Comment by ndepaola** [comment]
local files are now supported in the `id` field - if the `id` value refers to a valid filepath, the tool will upload this file to mpc; otherwise, it is treated as a google drive ID and the tool will attempt to download it :)
