### ISSUE TITLE
S27 cardstock not supported

### ISSUE THREAD

**Issue by iconmaster5326** [chilli-axe/mpc-autofill#195]
# System

- **Operating System (including version)**: Windows 10 - `10.0.19045 Build 19045`
- **Desktop Tool Version**: https://github.com/chilli-axe/mpc-autofill/releases/tag/v4.4
- **Browser (including version)**: N/A

# Affected Components

- [ ] Backend
- [ ] Frontend
- [X] Desktop Tool

# Description

MPC supports a new option for cardstock, S27:

![image](https://github.com/chilli-axe/mpc-autofill/assets/3768458/1a3d11e4-2241-4172-8943-dfa8bb0b24a8)

It's exactly the one I want to use, too. Nice and cheap. But when I try to use it in an order:

```
There was a problem with your order file:

Order cardstock (S27) Smooth not supported!

Press Enter to exit.
```

# Steps to Reproduce

Here's an order file that triggered this error: [order.xml.txt](https://github.com/chilli-axe/mpc-autofill/files/13260835/order.xml.txt)

**Comment by ndepaola** [comment]
howdy! it should be reasonably straightforward to add S27 support (the catch is that PrinterStudio doesn't do S27) - will involve frontend changes too - i'll post an update here if/when i get around to it

**Comment by ndepaola** [comment]
done - will be included in the next release :)
