### ISSUE TITLE
Vendors might have different size brackets

### ISSUE THREAD

**Issue by t-my** [chilli-axe/mpc-autofill#201]
# Description

- PrinterStudio has different brackets than MPC, see screenshots below:
![image](https://github.com/chilli-axe/mpc-autofill/assets/10090580/e90448cb-ac57-4ad1-a978-6d03e594bb5f)
![image](https://github.com/chilli-axe/mpc-autofill/assets/10090580/7bfa4d5d-1756-4b9d-98b5-c370c51a040a)

# Steps to Reproduce

- Create order with 54 cards and use PrinterStudio
- SeleniumError

**Comment by ndepaola** [comment]
ah shit - good pickup!! I'll focus on addressing this over the next week or two as my highest priority

**Comment by ndepaola** [comment]
done - will be included in the next release :)
