### ISSUE TITLE
DFCs get "card not found" errors when importing with double slash syntax

### ISSUE THREAD

**Issue by invalidCards** [chilli-axe/mpc-autofill#203]
# System

- **Operating System (including version)**: Windows 11 Pro 22H2 22621.2861
- **Desktop Tool Version**: N/A
- **Browser (including version)**: Firefox 121.0

# Affected Components

- [ ] Backend
- [x] Frontend
- [ ] Desktop Tool

# Description

- Double faced cards added to a project with the double slash syntax (i.e. `Growing Rites of Itlimoc // Itlimoc, Cradle of the Sun`) show a 404 Card Not Found error in the frontend due to the name being taken as a whole (resolving to `growing rites of itlimoc itlimoc cradle of the sun` as the "search query"). This is quite annoying as for instance Archidekt exports decks with this double-face syntax (and I believe the URL import does so as well). Correctly adding the double-faced card requires completely removing the slot and manually adding only the front to the project, as editing the search query doesn't update the cardback automatically.

![image](https://github.com/chilli-axe/mpc-autofill/assets/842080/5ac2b054-44f6-498a-ac37-86050f4ed5ff)
![image](https://github.com/chilli-axe/mpc-autofill/assets/842080/5e0435e5-de20-42a0-8405-e9526d043967)

# Steps to Reproduce

- Open a new editor project
- Add Cards -> Text, then try adding any double-faced card with the syntax for both faces. Examples:
  - Growing Rites of Itlimoc // Itlimoc, Cradle of the Sun
  - Toralf, God of Fury // Toralf's Hammer
  - Azusa's Many Journeys // Likeness of the Seeker

**Comment by ndepaola** [comment]
i'll address this by changing the face delimiter in the text importer from `|` to `//`, then later down the track i'll look at adding some configuration options for users to change the delimiters the importer uses
