### ISSUE TITLE
An uncaught exception occurred: An error occurred while attempting to configure the webdriver for your specified browser.

### ISSUE THREAD

**Issue by davidianstyle** [chilli-axe/mpc-autofill#204]
# System

- **Operating System (including version)**: MacOS Sonoma 14.2.1
- **Desktop Tool Version**: [87a1305](https://github.com/chilli-axe/mpc-autofill/wiki/Desktop-Tool/87a1305568ad59e7d872b450f62fe3166b92491c)
- **Browser (including version)**: Chrome Version 120.0.6099.216

# Affected Components

- [ ] Backend
- [ ] Frontend
- [x] Desktop Tool

# Description

Error when running desktop tool: `An uncaught exception occurred: An error occurred while attempting to configure the webdriver for your specified browser. Please make sure you have installed the browser & that it is up to date:  Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home   Press Enter to exit`

Resolved by running `brew install chromedriver` and allowing app to run in Settings > Privacy & Security > Allow applications downloaded from "App Store and identified developers"

# Steps to Reproduce

- `$ python3 ~/mpc-autofill/desktop-tool/autofill.py`

**Comment by davidianstyle** [comment]
_(reposting resolution here for others to find more easily)_

Resolved by running `brew install chromedriver` and allowing app to run in Settings > Privacy & Security > Allow applications downloaded from "App Store and identified developers"

**Comment by ndepaola** [comment]
it looks like you're running the source code directly rather than using the pre-compiled executables - did you `pip install --upgrade -r ~/mpc-autofill/desktop-tool/requirements.txt` before running it? if you did, could you paste your `pip freeze` here pls?

**Comment by davidianstyle** [comment]
Sorry, that's my fault. I didn't run `pip install --upgrade -r ~/mpc-autofill/desktop-tool/requirements.txt` before running the source code directly. I'll definitely make note to do that next time I pull down the latest changes in case the dependencies change.

**Comment by ndepaola** [comment]
no problem!! 🚀
