### ISSUE TITLE
website card load failed

### ISSUE THREAD

**Issue by mafima** [chilli-axe/mpc-autofill#223]
https://mpcfill.com/new

![image](https://github.com/chilli-axe/mpc-autofill/assets/3407209/41fae590-3c24-47f8-8703-06969b33500e)

**Comment by jasonewall** [comment]
I'm also seeing this intermittently. Oddly enough when it happens, and I right click "view image in a new tab" for images that were previously successful, I get a 403 from google images, saying the rate limit exceeded for my IP.

**Comment by jasonewall** [comment]
Looks like there's a fix that's being tested on the beta site right now: https://mpcautofill.github.io. You'll have to manually set your server to: https://mpcfill.com

**Comment by ndepaola** [comment]
yea this is a known issue. at the moment we think google tightened their rate limit for thumbnails served from `drive.google.com`, so while there's always been potential for this to be a problem, it has started hitting many more users recently. https://mpcautofill.github.io is currently using an experimental feature targeted at solving this - essentially putting a CDN in front of `drive.google.com` - which i'm still actively developing and will look at rolling out more broadly when i think it's mature enough. see #220 for more discussion too

**Comment by ndepaola** [comment]
this is fixed now (i just haven't PR'd my cloudflare worker into the repo yet)
