### ISSUE TITLE
What servers for mpc GitHub.io

### ISSUE THREAD

**Issue by anok78** [chilli-axe/mpc-autofill#224]
# System

- **Operating System (including version)**: windows 11
- **Desktop Tool Version**:
- **Browser (including version)**: chrome, copilot Microsoft 

# Affected Components

- [ ] Backend
- [ ] Frontend
- [ ] Desktop Tool

# Description

Mpc fill not working, the one with GitHub.io asking for a server not sure what that means, want to get back to making my cards 

-

# Steps to Reproduce

-

**Comment by ndepaola** [comment]
https://mpcfill.com
