### ISSUE TITLE
Inserting the image stalls at random cards.

### ISSUE THREAD

**Issue by dperremans** [chilli-axe/mpc-autofill#227]
# System

- Operating system: MacOS
- Latest desktop tool version (downloaded it on March 25th)
- Chrome (123.0.6312.59)

# Affected Components

- [x] Desktop Tool

# Description

I've added a new cards.xml file to the same folder as the autofill-macos tool. When uploading the tools gets stuck at random cards.
Sometimes it upload to 80% and then stalls, so I have to terminate the process. And then other times, it uploads to 25%, ... 
I've tried it 5 times, but still the same issue.

The images are all downloaded. So I don't need to go through that process again.

The XML file is added to this issue. I've added it in a ZIP file.

# Steps to Reproduce

- Clicked on the macos-autofill tool.
- the terminal opens. I just press on enter to set the default options.
- I enter my MakePlayingCards credentials in my browser that was automatically opened.
- The process continues: it uploads my cards until it stalls at a random card.

[cards.zip](https://github.com/chilli-axe/mpc-autofill/files/14742220/cards.zip)

**Comment by dperremans** [comment]
I've found the solution for my issue:
- I've removed the whole cards folder with all the downloaded images
- Did the process again, downloading and uploading.

My guess is that there went something wrong while downloading the images. Maybe corrupt images?

**Comment by Moss-CG** [comment]
I am running in to this same issue and despite re-downloading images it never works and continually gets stuck on the 6th and 7th cards.
![image](https://github.com/chilli-axe/mpc-autofill/assets/1307487/395e7ba4-a937-4b62-8766-c5f5306e92d1)
[cards (3).zip](https://github.com/user-attachments/files/15906909/cards.3.zip)

**Comment by dennisperremans** [comment]
@Moss-CG Have do you have the latest version of the tool? And have you delete the cards folder itself? That worked for me. I have no problems on Windows or iOS

**Comment by jethrogb** [comment]
Same issue on Linux

**Comment by ndepaola** [comment]
a few people on discord have reported that refreshing the page when this happens can resolve it - could you guys try that next time it happens and report back?

**Comment by jethrogb** [comment]
I tried that. It sometimes continued with the next card, but the "current" card is then not properly inserted.

Running from git source instead of the released binary solved it for me.

**Comment by WilsonStewart** [comment]
@jethrogb Trying to run from the git source myself, having issues with the card downloads, thinking it had to do with the way I created the google api creds json, how did you go about doing that? (If you don't mind helping 😀 )

**Comment by joaobarcia** [comment]
I have experienced the exact same bug on linux, also with inserting into slot 7.

Reloading the page unstuck the process. The image for slot 7 was missing, but that was easy enough to add manually :)

Thanks for the amazing tool and let me know if I can provide any information that might help further debug the issue.

**Comment by nhiebert1776** [comment]
Same issue for me with with the windows tool. Stalls trying to insert into slot 7.  I used the most recent version of the tool as well as an old version I had saved from past uploads. I've used successfully many times in the past. Tried from two different browsers as well as two different computers.  Tried deleting the card that initially was getting stuck from the xml but it would just get stuck on a new card, around slot 7.  The one thing I noticed is that it was trying to insert this card shortly after the first save of the project on makeplayingcards.com browser window.  That initial save seems to take a hair longer than the subsequent saves and I wonder if the tool just isn't waiting long enough for that first save to complete before attempting to continue.  A refresh of the browser got it going again and I had to manually add the 1 skipped image.

**Comment by raphabenoi** [comment]
I'm having the same issue — also on MacOS.
I have to refresh every couple minutes as it fails to insert images "relatively" frequently, e.g. 17 times out of 372 cards project. So on average about every 20 cards but sometimes they are just a few cards apart and then it's fine again for a bigger batch :D

**Comment by ndepaola** [comment]
thanks for the detailed error reports - a few people have reported this issue on discord over the last week too. i haven't been able to reproduce this reliably, but when i have, it seems the entire MPC frontend locks up after the tool saves the project - the grey loading overlay is visible and no UI elements can be interacted with. it seems like this is down to a code change MPC pushed to their site recently

could you @nhiebert1776 @raphabenoi run the tool with the command line arg `--debug-logs`, then when the tool freezes like this, upload the debug log file `autofill_log.txt` here? 🙏

atm i'm looking at resolving this by detecting when the MPC frontend has locked up while processing a change & refreshing the page before proceeding

**Comment by raphabenoi** [comment]
I haven't had the chance to run it again with `--debug-loggs` but I "successfully" managed to upload almost all images without errors by just saying NO to the question on auto saving when initializing.

**Comment by ndepaola** [comment]
i have a fix going for this locally - just testing it a little more before pushing. will create a new release with this fix when it's ready
