### ISSUE TITLE
Site wont let me choose card backs or add xml order

### ISSUE THREAD

**Issue by TheWanderingMalachi** [chilli-axe/mpc-autofill#228]
# System

- **Operating System (including version)**: Newest Windows Update
- **Desktop Tool Version**:
- **Browser (including version)**: Chrome newest version

# Affected Components

- [ ] Backend
- [ ] Frontend
- [ ] Desktop Tool

# Description

 the site says syntax error along with something going wrong with json 

-

# Steps to Reproduce

-

**Comment by ndepaola** [comment]
thanks for your patience - @Investigamer is currently working through some server issues with https://mpcfill.com. i'll post an update here when these issues have been resolved

**Comment by ndepaola** [comment]
this issue should now be resolved, thanks for bearing with us!
