### ISSUE TITLE
Site seems locked in loading after submitting list

### ISSUE THREAD

**Issue by flokjela** [chilli-axe/mpc-autofill#231]
# System

- **Operating System (including version)**: Windows 10 Home
- **Desktop Tool Version**: 
- **Browser (including version)**:  Chrome123.0.6312.59

# Affected Components

- [x] Backend
- [x] Frontend
- [ ] Desktop Tool

# Description

- I inserted a list of 7 cards, images took forever loading. After I tried again I got random errors on the website and couldn't submit a new list in the add cards menu. Restarting browser produced same result. Seems entirely broken, not usable at least. Also option doesn't show any drives but that might be because site backend crashed.

# Steps to Reproduce

 it keeps repeating no matter what I try
 Does not seem random, same thing in other browsers

-

**Comment by flokjela** [comment]
![image](https://github.com/chilli-axe/mpc-autofill/assets/13423572/86c65431-d6f3-446d-b14e-1f68f9596a00)

**Comment by ndepaola** [comment]
howdy - this is an issue with the mpc fill deployment specifically, not a software bug - so this issue should be raised here https://github.com/MrTeferi/mpc-fill/
