### ISSUE TITLE
Website not loading card images

### ISSUE THREAD

**Issue by copperflamex** [chilli-axe/mpc-autofill#232]
# System

- Edition	Windows 10 Pro
Version	22H2
OS build	19045.4170
Experience	Windows Feature Experience Pack 1000.19054.1000.0
:
- n/a - website (https://mpcautofill.github.io/editor)
- :
- Version 123.0.6312.87 (Official Build) (64-bit)
- :

# Affected Components

- [ ] Backend
- [ x] Frontend
- [ ] Desktop Tool

# Description

I'm not sure if someone has already reported this (please remove if so).  When attempting to add cards to a project, no data ever loads (see screenshot).
![image](https://github.com/chilli-axe/mpc-autofill/assets/165074953/ce2ab180-87d6-4405-bda3-8f6403eaee14)
![Screenshot 2024-03-26 133314](https://github.com/chilli-axe/mpc-autofill/assets/165074953/4bd47b11-d2e1-447b-95c7-a60f5dc3ec2f)

-

# Steps to Reproduce

Attempt to load cards via Text Editor.
Website has not loaded any images, rebooted browser.
Added via Text list (+300 entries though)
(https://mpcfill.com/editor)

-

**Comment by ndepaola** [comment]
howdy - this is an issue with the mpc fill deployment specifically, not a software bug - so this issue should be raised here https://github.com/MrTeferi/mpc-fill/
