### ISSUE TITLE
Website not working correctly. Can't search for cards.

### ISSUE THREAD

**Issue by joeg77** [chilli-axe/mpc-autofill#233]
# System

- **Operating System (including version)**:
- **Desktop Tool Version**:
- **Browser (including version)**:

# Affected Components

- [ ] Backend
- [ ] Frontend
- [ ] Desktop Tool

# Description

-

# Steps to Reproduce

-

**Comment by ndepaola** [comment]
howdy - this is an issue with the mpc fill deployment specifically, not a software bug - so this issue should be raised here https://github.com/MrTeferi/mpc-fill/
