### ISSUE TITLE
Images no longer loading and Text editor submit button always disabled

### ISSUE THREAD

**Issue by AdamElaoud** [chilli-axe/mpc-autofill#234]
# System

- **Operating System (including version)**: Windows 10
- **Desktop Tool Version**: N/A
- **Browser (including version)**: Chrome 123.0.6312.86

# Affected Components

- [x] Backend
- [x] Frontend

# Description

**Problem:** Images do not load in seemingly the same fashion as the previous problem that presented a few days ago
**Expected Behavior:** images load

![image](https://github.com/chilli-axe/mpc-autofill/assets/26557517/ae1501c3-0494-4943-80d4-17586af34d4f)
![image](https://github.com/chilli-axe/mpc-autofill/assets/26557517/31cfb5cd-f29b-42ec-8497-b538ab293517)

**Problem:** When attempting to add cards to the editor, the submit button is always greyed out
**Expected Behavior:** the submit properly enabled itself when appropriately formatted card names are entered into the text editor
**Full prompt provided to the editor:**
```
t:Goblin Shaman
Dark Ritual
Cabal Ritual
2x Teferi, Master of Time
Dack Fayden
Elspeth, Sun's Champion
4x Jace Vryn's Prodigy
2x Glaring Spotlight
```

![image](https://github.com/chilli-axe/mpc-autofill/assets/26557517/621714d2-ba53-44d6-98e9-26f424c53432)

# Steps to Reproduce

1. navigate to website
2. open editor

**Comment by Townsmith** [comment]
Same issue here

**Comment by AdamElaoud** [comment]
issue seems to have resolved itself, images are now appearing as expected and the text editor is functioning
