### ISSUE TITLE
An uncaught exception occurred: unhashable type: 'AutofillDriver'

### ISSUE THREAD

**Issue by h3rb1n4t0r** [chilli-axe/mpc-autofill#236]
# System

- **Operating System (including version)**: Debian 12 on Kernel 6.1.0-20-amd64
- **Desktop Tool Version**: v4.5
- **Browser (including version)**: Brave v 1.65.123 | Chrome Version 124.0.6367.118 (Official Build) (64-bit)

# Affected Components

Not 100% sure if my selection is correct.

- [ ] Backend
- [ ] Frontend
- [X] Desktop Tool

# Description

## Issue
The Image Upload Batch starts, but yields the following interruption for some cards during the process:
```
An uncaught exception occurred:
unhashable type: 'AutofillDriver'

? How should the tool proceed? 
  Retry this action
❯ Skip this action
  Terminate
```
Retrying fails. Skipping skips upload of the respective card.

## Expected Behaviour
Upload works in full and without manual intervention.

# Steps to Reproduce

Problem is reproducable with two different XML sets of around 110 entries originally stemming from Archidekt, copied over to MPC-fill without unnecessary information (things that follow the card name in syntax format 3) and exported as XML.

[Archive.zip](https://github.com/chilli-axe/mpc-autofill/files/15172037/Archive.zip)

# Additional aspects
Although I do not suspect root causes within the following, I will disclose for full transparency: Running KDE on X11 Plasma with Bismuth as Tiling Window Manager with files and executable being stored on a SMB share mounted with rclone.

**Comment by ndepaola** [comment]
thanks for letting me know about this - i'll investigate and keep this thread updated with my progress

**Comment by h3rb1n4t0r** [comment]
Prior version works smoothly so far. I noticed that it names the project in format "Name - YYYY-MM-DD" as opposed to the newest version, where it was "Projekt-/randomstring/"

**Comment by ndepaola** [comment]
thanks for the bug report, i'll put out a hotfix release shortly

the issue you noticed is related - it was an issue with the code that formulates the project name string (Project-/randomstring/ is the MPC/Printerstudio default)
