### ISSUE TITLE
As an autofill user with a large order, I would like to be able to pause and resume uploads.

### ISSUE THREAD

**Issue by candyapplecorn** [chilli-axe/mpc-autofill#24]
As a user uploading 400+ cards, **inevitably** my internet goes down during the several hour upload process. This ruins the order. Currently I cannot actually use the autofill script to successfully fill large orders.

In order to fulfill large orders, I propose a new feature, where the autofill script first checks to see if a card slot is already filled. If it's filled, then the script will not re-upload the card for that slot. In this manner, the script can quickly "catch up" to where previous executions had left off. 

This feature would allow the user to both save mid-project, as well as put their computer to sleep and take several days to complete a large order upload.

**Comment by candyapplecorn** [comment]
@ndepaola I can take a hack at this after work sometime this week. I've done similar work before. I could use any advice or tips you've got though.

**Comment by candyapplecorn** [comment]
PR: https://github.com/ndepaola/mpc-autofill/pull/25

**Comment by candyapplecorn** [comment]
Here's a screenshot of the script running in a Chrome web driver session that's signed in, with a selected project. I've already closed and re-started the script several times with this project.

![image](https://user-images.githubusercontent.com/5856981/122298105-2fb73080-ceb1-11eb-96b3-718e2e0fbc98.png)

**Comment by earthsdm** [comment]
I tested resuming an order with the `-skipsetup` argument last night and it worked great. Thank you @candyapplecorn 😃
