### ISSUE TITLE
Card Life//Death not in the database

### ISSUE THREAD

**Issue by TacoToad** [chilli-axe/mpc-autofill#240]
# System

- **Windows 10**:
- **N/A**:
- **Browser (current)**:

# Affected Components

- [ ] Backend
- [ ] Frontend
- [ ] Desktop Tool

# Description

-

# Steps to Reproduce

-

**Comment by ndepaola** [comment]
howdy! the mpc autofill software on its own has no concept of cards in tabletop games - it just tracks whatever images the server has access to. issues in this repo are meant for tracking bugs/feature requests/etc in the software, not the images it's tracking.

it sounds like you're talking about mpcfill.com - problems with the image database should be reported in the discord server. btw i can see 12 results for life // death on mpcfill.com - try searching for it as `life death`. you may need to widen your search settings too.
