### ISSUE TITLE
Cards Do Not Load in Editor

### ISSUE THREAD

**Issue by Exokyhh** [chilli-axe/mpc-autofill#274]
# System

- **Windows 11**:
- **Firefox 133.0.3**:

# Affected Components

- [x] Backend
- [x] Frontend
- [ ] Desktop Tool

(can be both I have no idea)

# Description

- I keep getting this error when I try to edit any MPC Project. My cards doesn't load, not even the card back. I don't get it, I tried different browsers, tried to delete the cache, cookies. Nothing worked.
![Screenshot 2024-12-29 223849](https://github.com/user-attachments/assets/9b3adacc-74c3-418f-9b12-011d8a080ade)

# Steps to Reproduce

- No idea how to reproduce this, it just happened after I've done my first order. Now I can no longer use the tool to order more cards.

**Comment by ndepaola** [comment]
Howdy - thanks for the bug report. Could you follow these steps and upload the resulting file to this thread so I can debug further?

* Load MPC Autofill front page
* Right click -> Inspect Element -> open the Network tab
* Load Editor page
* Add a few cards by text:
 ```
4x opt
3x char
```
* Wait until you get the error message you showed
* Export as HAR file. This will be accessed in a different menu depending on your browser - e.g. in Firefox:
  ![image](https://github.com/user-attachments/assets/4be47730-cc34-48f7-87f6-6210e3408fa8)
* Upload HAR file to this thread

**Comment by Exokyhh** [comment]
Oh god, I found out what was causing all the issues. It was Kaspersky, the Antivirus. I saw there were many request from it, and when I disabled it, it loaded correctly -_-
[Har File.zip](https://github.com/user-attachments/files/18277476/Har.File.zip)

**Comment by ndepaola** [comment]
No worries! Your best bet from here is probably to add an exception for MPC Autofill in Kaspersky. Closing this thread as I don't think there's anything to fix on my end.
