### ISSUE TITLE
Add client_secrets.json example

### ISSUE THREAD

**Issue by CollinLeishman** [chilli-axe/mpc-autofill#32]
What should the keys in `client_secrets.json` be? Could we get an example of what one would look like? Thanks!

**Comment by bwsinger** [comment]
I made a PR that updates the README with a bunch of stuff to help set up the environment: https://github.com/chilli-axe/mpc-autofill/pull/33

Step 8 in Setup shows you how to get your client_secrects.json file: https://github.com/chilli-axe/mpc-autofill/blob/afc982cb8b3ae7fcf9f8b2ebd1846f17494ac7dc/README.md

**Comment by bwsinger** [comment]
Here's an example file for reference (with the fields removed for privacy):

```
{
  "type": "service_account",
  "project_id": "<Google_project_name>",
  "private_key_id": "<long_character_string>",
  "private_key": "<ssh_style_private_key>",
  "client_email": "<email>",
  "client_id": "<number>",
  "auth_uri": "<url>",
  "token_uri": "<url>",
  "auth_provider_x509_cert_url": "<url>",
  "client_x509_cert_url": "<url>"
}
```

**Comment by CollinLeishman** [comment]
Thank you @bwsinger!
