### ISSUE TITLE
Step by step setup guide to run the app locally

### ISSUE THREAD

**Issue by ners10100100** [chilli-axe/mpc-autofill#38]
It's not an issue, I know, but for more unexperienced people like myself it is really hard to setup the project without detailed instruction. I would be really thankful if the setup part could be more detailed and more like a step by step approach. Thank you in advance!

**Comment by chilli-axe** [comment]
this is being addressed by PR #33 :)

**Comment by ners10100100** [comment]
Oh, thank you very much! I'll be patiently waiting then! "Issue" can be closed then!

**Comment by ThePawPaw** [comment]
Would be keen on getting this to occur. I feel completely overwhelmed as a beginner to doing anything of this sort, and have to take an extensive amount of time every step in this guide. I am now stuck, with a lot of assumed knowledge for steps 9 onwards. Hoping a comprehensive step-by-step is coming soon
