### ISSUE TITLE
Images not found

### ISSUE THREAD

**Issue by derekchiang** [chilli-axe/mpc-autofill#48]
Hey guys, I got the web app up and running locally, but it can't find any images when I submit the cards.

Am I right in understanding that the Google Drive folders I provide need to contain those images?  If so, is there a public drive available that already has the images?  If not, how do I go about acquiring those images?

Thanks,
Derek

**Comment by fklemme** [comment]
MPCAutofill is relying on external image sources via Google Drives. Some drives can be found on the [Reddit community](https://www.reddit.com/r/mpcproxies/). Support for local files is coming soon.

**Comment by fklemme** [comment]
Also, check if the drives are still available. After [the latest events](https://www.reddit.com/r/mpcproxies/comments/pt6ekf/state_of_the_subreddit_moving_forward/), many drives have been taken offline.

**Comment by derekchiang** [comment]
@fklemme that solved the issue.  Thank you very much!
