### ISSUE TITLE
Pick high DPI images by default

### ISSUE THREAD

**Issue by derekchiang** [chilli-axe/mpc-autofill#49]
When printing hundreds of cards, it gets tiring to have to click through the images to get to the higher-DPI images.  Is there any way to order the images by DPI by default?

**Comment by ndepaola** [comment]
the reworked frontend includes DPI filtering - while this doesn't enable you to pick high DPI images by default, i think it still accomplishes the spirit of what you're trying to do, which is ignore low DPI images. the public beta for the reworked frontend is available now - you can access it with the mpcfill.com database at https://mpcautofill.github.io?server=https://mpcfill.com - so i'm closing this issue as completed.
