### ISSUE TITLE
Stuck loading indefinitely

### ISSUE THREAD

**Issue by Katreyasaunt** [chilli-axe/mpc-autofill#54]
When using this program to upload to MPC it will get "stuck" on certain cards while trying to upload them. The image of the card will show as uploaded within the library, but the upload will continually try and upload the same card and never assign it to a card slot.

**Comment by Katreyasaunt** [comment]
![image](https://user-images.githubusercontent.com/95343591/144379886-f7779b6d-b211-4c0a-83ca-27b8158d9453.png)
For reference, it is essentially stuck like this. Sometimes it is able to brute force through a card that it is stuck on after a long time, but even after leaving it running for four hours I was not able to get through even one order.

**Comment by Forgenn** [comment]
This problem was fixed in #51, but it has not made it to any releases yet. You can download autofill.py and run it yourself while there isn't a release.

**Comment by Katreyasaunt** [comment]
Oh I see! I have no idea what to do. Do I just copy the string into the exe file whenever I run it?

**Comment by Forgenn** [comment]
I have released an autofill.exe compiled with the fix while the owner doesn't update it, you can find it here. https://github.com/Forgenn/mpc-autofill/releases/tag/v3.4.2
