### ISSUE TITLE
Progress bar not updating when downloading images

### ISSUE THREAD

**Issue by johtso** [chilli-axe/mpc-autofill#55]
I can see the images are being downloaded, but for some reason the progress bar isn't being updated.

Mac OS.

**Comment by ndepaola** [comment]
the progress bar code has been updated in the latest release https://github.com/chilli-axe/mpc-autofill/releases/tag/v4.0 could you give this a spin and see if the issue persists for you?

**Comment by ndepaola** [comment]
Closing this issue for now - feel free to reopen if it persists in the new version
