### ISSUE TITLE
"Sorin, Solemn Visitor" name matching to emblem instead of Planeswalker

### ISSUE THREAD

**Issue by axlan** [chilli-axe/mpc-autofill#57]
Adding "Sorin, Solemn Visitor" in the  autofill list will create an entry for the emblem instead of the main card.

I can get around this by disabling cards from "warpdandy" or by importing the card from an XML order.

It happens with both precise and fuzzy search.

**Comment by MrTeferi** [comment]
This is pretty normal, also feel free to direct any concerns relating to the mpcfill.com site itself to my forked repo here, which tracks code changes on the deployed version of the site:
https://github.com/MrTeferi/mpc-fill

I'm not sure if Chilli or the others will be contributing to the master repo anytime soon as they are currently MIA :(

**Comment by ndepaola** [comment]
this is not a code issue - it purely depends on the naming conventions followed by images in drives connected to the site
