### ISSUE TITLE
Some issues with cardback field when using local images or the "-skipsetup" flag

### ISSUE THREAD

**Issue by axlan** [chilli-axe/mpc-autofill#59]
For a recent order I wanted to do the following:

1. Create an order using http://mpcfill.com/ with 551 cards.
2. Use `autofill.py` normally to create an order on MPC and save the order.
3. Generate an order with cards I made on my local computer using the script I made https://gist.github.com/axlan/21faf9c28b40904662124d20ff365f2b . The slots for the cards were generated to go from 551 to 611.
4. Use `autofill.py` with the `-skipsetup` flag to create the combined order of 612 cards.

This almost worked but the way the XML `cardback` value is handled required me to do some manual intervention.

The problem stems from wanting to either:
a. Using a local file for the cardback.
b. Using `-skipsetup` with different cardbacks for the different parts of the order.

The first issue would be relatively straightforward to fix. Unlike the other cards, the cardback isn't cached and can only be specified by ID. This could be fixed by allowing an optional filename to be specified.

The second issue is a bit harder. Probably the easiest way would be to add more robust logic for "appending" to an order like I was doing here so that the offsets for the slots are handled automatically. This could be a different CLI flag, or just instructions for a better way to do this sort order.

**Comment by ndepaola** [comment]
the latest release https://github.com/chilli-axe/mpc-autofill/releases/tag/v4.0 allows you to refer to local files in the `id` field for cards, including the common cardback - could you give it a try and see if it suits your use case?

**Comment by axlan** [comment]
Looks good, thanks.
