### ISSUE TITLE
mpcfill.com - The back of double-faced cards doesn't always load

### ISSUE THREAD

**Issue by bwsinger** [chilli-axe/mpc-autofill#63]
When loading a card by changing its name on the card preview UI, it doesn't load the corresponding card back for double-faced cards.

Video demonstration: https://www.loom.com/share/ecac8085ab3b488a93b8b3661e793d90

**Comment by ndepaola** [comment]
sorry for forgetting to reply to this. the frontend is working as intended here - the fronts of double-faced cards are only matched to their backs when you add new cards, not when you modify existing cards. i suppose we could include a modal which asks the user whether to automatically query the back face when you change the query for a card front to the front of a double-faced card pair, but that seems like a fairly niche case to me. instead i think it's fine for the user to have to manually type in the name of the back of the dfc pair when changing queries in-place.
