### ISSUE TITLE
Feature Request: Orders over 612 and/or multiple xml files at once

### ISSUE THREAD

**Issue by justingolden21** [chilli-axe/mpc-autofill#65]
Feature Request 1:

It would be cool if an order file could contain over 612 items, and each additional order would just spill into a new "deck."

Additionally, it could be  "intelligent" and divide up the numbers better too, but that's just a bonus

Feature Request 2:

Scanning all xml files in the adjacent / root directory and combining them

Alternatively, a script to combine them. Currently combining one at a time and then changing card backs by editing the XML in VS Code.

Thanks and love this software so much 😄

**Comment by ndepaola** [comment]
i have put these onto the todo list :)
