### ISSUE TITLE
Feature Request: Chrome Alternatives

### ISSUE THREAD

**Issue by ToMuchNeverEnuf** [chilli-axe/mpc-autofill#69]
I know this is probably a herculean task but  it would be handy to be able to use something other than chrome. I have been using the Brave browser which is on the chrome architecture, I know the new edge is as well (for the few sad souls who use edge). I'm wondering if there would be a simple way to designate a different program to run this through and still have it function.

**Comment by ndepaola** [comment]
done :) https://github.com/chilli-axe/mpc-autofill/commit/34ac75162a8fbb2aa9ff40d39994e5f98f359fbd
