### ISSUE TITLE
[Feature Request] Printerstudio.com Compatibility

### ISSUE THREAD

**Issue by Spottyfriend** [chilli-axe/mpc-autofill#82]
This may not be do-able since I know nothing about coding, but since Printer Studio has a pretty much identical UI to MPC (as well as being the same company in disguise as far as I understand it), it might be possible and therefore worth asking:

Could you give the tool compatibility with MPC's sister site printerstudio.com? This would be extremely useful since this is what some in EU/UK have used to get around large import tax/duties on purchases from MPC.

Of course fair enough if that'd be an unworkable task.

**Comment by ndepaola** [comment]
this has been on the todo list for a little while but i haven't gotten around to it yet - i imagine they share the bulk of their javascript code so hopefully it should be workable - will keep you posted :)

**Comment by Spottyfriend** [comment]
That'd be amazing! Opens up usage of this excellent tool to a large group of people who it wouldn't necessarily benefit before - thanks!

**Comment by Spottyfriend** [comment]
If you do get around to this, Discord user verxus indicated that they got autofill working with printerstudio on 3rd October. ([See here](https://discord.com/channels/889831317066358815/898301677080297474/1026576733819912302))

**Comment by luhacky** [comment]
Has the mentioned compatibility fix been implemented yet?
