### ISSUE TITLE
Autofill isn't accurately uploading the correct images to MPC

### ISSUE THREAD

**Issue by grandmerchant** [chilli-axe/mpc-autofill#83]
While importing a 612 card order using autofill, I'm seeing wild inaccuracies after the script completes. I'm guessing only about 60-70% of the images are correct. The remaining cards are images of other cards in my order. Double sided cards are also sometimes getting the wrong card backs. No specific pattern is jumping out at me to explain in the inaccuracies. Talked with folks in the Discord and other folks are also experiencing this.

**Comment by thro86** [comment]
Having the same issue right now. Trying to fill a 504 card order and it's doubling images, misplacing images, not uploading some images. Total mess. Hopefully we can get some sort of fix for this soon. My order was taking roughly 9 hours to complete uploading and even then it was still a total mess :(.

Thank you for all that you do. If you could look into this issue I would greatly appreciate it. Saw some people on the bootleg discord also talking about this issue.

**Comment by aapkov** [comment]
I have the same issue, some uploads are failing

![ss](https://user-images.githubusercontent.com/83282311/192133300-7d90b2cd-c462-4970-b596-a9966df8a682.png)

**Comment by ndepaola** [comment]
This should be fixed by https://github.com/chilli-axe/mpc-autofill/pull/85 :) when that PR looks good and is merged in + a release has been created with the fix, I'll close this issue

**Comment by ndepaola** [comment]
fixed in the latest release :) please reopen this issue if the problem persists
