### ISSUE TITLE
CSRF verification failed when visiting 'http://localhost:8000'

### ISSUE THREAD

**Issue by davidianstyle** [chilli-axe/mpc-autofill#91]
![Screen Shot 2022-10-20 at 2 26 25 PM](https://user-images.githubusercontent.com/6446624/197028638-5fc49c2b-f3d5-42b9-b02e-3e5105e43663.png)

Seems to work fine when using 'http://127.0.0.1:8000'

**Comment by ndepaola** [comment]
fixed by https://github.com/chilli-axe/mpc-autofill/pull/92, thank you for your contribution!
