### ISSUE TITLE
Server accessible via http://localhost:80 but not via the network (http://[local IP address]:80)

### ISSUE THREAD

**Issue by davidianstyle** [chilli-axe/mpc-autofill#97]
Am I doing something wrong?

![image](https://user-images.githubusercontent.com/6446624/198199395-004a4b50-d540-4acb-960c-f56158cb35af.jpeg)

![image](https://user-images.githubusercontent.com/6446624/198199408-6073c169-af93-469a-96ca-65bbfd9d7e38.jpeg)

Maybe I'm missing something in my configuration?

**Comment by ndepaola** [comment]
by default, the django server is configured through the `ALLOWED_HOSTS` setting to be available on localhost and 127.0.0.1. you can set up an `.env` file to update this such that your server is available on 192.168.1.22 - check out this file https://github.com/chilli-axe/mpc-autofill/blob/master/MPCAutofill/MPCAutofill/.env.dist lmk how you go with this :)

**Comment by davidianstyle** [comment]
I tried explicitly adding `192.168.1.22` in `$working_directory/mpc-autofill/MPCAutofill/MPCAutofill/.env`:
```
# Change allowed hosts to * to allow outside access
ALLOWED_HOSTS=localhost,127.0.0.1,192.168.1.22
PREPEND_WWW=False
```
as well as setting `ALLOWED_HOSTS=*`

and still get the following:
![Screen Shot 2022-10-27 at 10 04 26 AM](https://user-images.githubusercontent.com/6446624/198307779-ff659535-0c49-42e4-8a6b-5d8bd269f41f.png)

**Comment by davidianstyle** [comment]
nginx logs don't seem all that helpful either:

192.168.1.22 request:
```
docker-nginx-1          | 172.30.0.1 - - [27/Oct/2022:14:03:26 +0000] "GET / HTTP/1.1" 400 154 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" "-"
docker-nginx-1          | 172.30.0.1 - - [27/Oct/2022:14:03:26 +0000] "GET /favicon.ico HTTP/1.1" 400 154 "http://192.168.1.22/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" "-"
```

localhost request:
```
docker-nginx-1          | 172.30.0.1 - - [27/Oct/2022:14:03:56 +0000] "GET / HTTP/1.1" 200 4495 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" "-"
docker-nginx-1          | 172.30.0.1 - - [27/Oct/2022:14:03:56 +0000] "GET /static/js/index.bundle.fe2a21fd9d60.js HTTP/1.1" 200 191315 "http://localhost/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" "-"
docker-nginx-1          | 172.30.0.1 - - [27/Oct/2022:14:03:56 +0000] "GET /static/css/index.bundle.963706c8d8f2.css HTTP/1.1" 200 159713 "http://localhost/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" "-"
```

**Comment by davidianstyle** [comment]
Found the solution here:
https://blog.anvileight.com/posts/how-to-fix-bad-request-400-in-django/

You were right about it being an issue with `ALLOWED_HOSTS`, I just needed to format the array correctly with parenthesis and double quotes:
```
# Change allowed hosts to * to allow outside access
ALLOWED_HOSTS=("localhost","127.0.0.1","192.168.1.22")
PREPEND_WWW=False
```

I'll submit a PR to `.env.dist` so that this is not a problem for others in the future.

**Comment by davidianstyle** [comment]
Submitted PR #98 for your review - thanks again for your help @ndepaola!

**Comment by davidianstyle** [comment]
Oops...I may have spoken too soon -.-
![Screenshot 2022-10-27 at 11 55 42 AM](https://user-images.githubusercontent.com/6446624/198340505-1f7908a5-dea3-47b4-94bd-06332a8705f0.png)

I think the only thing I changed was to revert `docker-compose.yml` back to serving the WebApp on port 8000 (instead of 80). I can't even get it back to working as I had it before when exposing the WebApp via port 80...

I'm really confused as what I did to actually get it working in the first place and what I did to break it again.

**Comment by davidianstyle** [comment]
@ndepaola - I submitted PR #99 to address this issue. This change will prevent overwriting an existing `.env` file and provide one copying from `.env.dist` if one doesn't already exist.

**Comment by davidianstyle** [comment]
![Screenshot 2022-10-27 at 11 06 43 PM](https://user-images.githubusercontent.com/6446624/198506321-baa2e7b4-a5fe-4544-865d-e52ee3634d86.png)

**Comment by ndepaola** [comment]
fixed in the mentioned PR, thank you for your contribution!
